### ISSUE TITLE
GitHub Directory radiation_pattern_drone auf 'public' stellen

### ISSUE THREAD

**Issue by HB9GYF** [HB9UF/radiation_pattern_drone#15]
Daniel, Mathias und Martin sind am 15.04.2021 übereingekommen, dass es an der Zeit ist, das Directory 'public' zu stellen. Wir wollen so u.a. mal testen, wie das mit anderen uns noch nicht bekannten Personen/Interessierten/Nachbauern/auch ggfs. Bauenden so in GitHub abläuft. Anscheinend gibt es bereits "potentielle Leser" aus dem USKA-Bereich, so hat Martin die Meldungen aufgefasst. 

Das Kernteam soll/darf weiterhin alles verändern, erstellen, mutieren können. Die "neuen" dürfen nur als Viewer ins Directory sehen können und dürfen nichts verändern. 

Martin wird in der Rolle als Projektleiter mit dem GitHub Status 'public' so die Möglichkeit bekommen mit der GitHub Funktion "Insight" eine wesentlich bessere Übersicht bezüglich "Merges" zu gewinnen.

**Comment by mweyland** [comment]
Ist erledigt, sorry dass ich das vergessen hatte.
