### ISSUE TITLE
Alte Issues nicht mehr gefunden

### ISSUE THREAD

**Issue by HB9GYF** [HB9UF/radiation_pattern_drone#19]
Wir hatten nach Martin verschiedene alte und gelöste Issues. Diese hat Martin am 08.05.2021 nicht mehr gefunden. Warum ist das so?  Ich hatte doch einen Issue für das SDR PCB erfasst und den Daniel HB9GVD zugeteilt. Den wollte ich jetzt mal sehen und bearbeiten. Wo ist dieser Issue?

**Comment by mweyland** [comment]
Wenn ein issue geschlossen wird, erscheint es nicht mehr in der Liste offener issues. Man kann aber beim Suchfenster den Filter `is:open` herauslöschen und dann sieht man alle issues...

**Comment by HB9GYF** [comment]
Ja, das stimmt. Man muss im Suchfenster sein und darf nicht auf einem (1) Issue "stehen. Man muss dann zurück gehen und hier löschen.

**Comment by HB9GYF** [comment]
Der Issue wird nun geschlossen.
